export enum Event {
  AUTH_INIT = 'AUTH_INIT',
  SHARE_VEHICLES_DATA = 'SHARE_VEHICLES_DATA',
  SHARE_ACCOUNT_DATA = 'SHARE_ACCOUNT_DATA',
  EXECUTE_ADVANCED_TRANSACTION = 'EXECUTE_ADVANCED_TRANSACTION',
  SIGN_MESSAGE = 'SIGN_MESSAGE',
  PROVISION_DEVELOPER_LICENSE = 'PROVISION_DEVELOPER_LICENSE',
}

export enum EventByUiState {
  VEHICLE_MANAGER = Event.SHARE_VEHICLES_DATA,
  ACCOUNT_MANAGER = Event.SHARE_ACCOUNT_DATA,
  ADVANCED_TRANSACTION = Event.EXECUTE_ADVANCED_TRANSACTION,
  SIGN_MESSAGE = Event.SIGN_MESSAGE,
  PROVISION_DEVELOPER_LICENSE = Event.PROVISION_DEVELOPER_LICENSE,
}
