export enum Event {
  AUTH_INIT = 'AUTH_INIT',
  SHARE_VEHICLES_DATA = 'SHARE_VEHICLES_DATA',
  ADVANCED_TRANSACTION_DATA = 'ADVANCED_TRANSACTION_DATA',
}

export enum EventByUiState {
  VEHICLE_MANAGER = Event.SHARE_VEHICLES_DATA,
  ADVANCED_TRANSACTION = Event.ADVANCED_TRANSACTION_DATA,
}
